### ISSUE TITLE
Can CODA be used for combo-Seq data from plant samples or others?

### ISSUE THREAD

**Issue by Xiao-Zhong** [marta-nazzari/CODA#1]
RT. Thank you!

**Comment by marta-nazzari** [comment]
Hi Xiao,
Absolutely! In the `coda_preprocess.sh` script you just need to provide the correct annotation `.fasta` and `.gtf` files of your genome of interest for `RSEM`. For `miRge3.0` it's a bit less straightforward, in the sense that the ready-to-use libraries provided by the authors are for human, mouse, rat, nematode, fruit fly, zebrafish and hamster. However, they provide a way to create custom libraries. Check https://mirge-build.readthedocs.io/en/latest/index.html.    

Hope that helps!

Best,
Marta

**Comment by cement-head** [comment]
WOW! This is awesome!  I've been trying to figure out how to adapt exceRpt to ZF for a while - thank you so much!

**Comment by marta-nazzari** [comment]
> WOW! This is awesome! I've been trying to figure out how to adapt exceRpt to ZF for a while - thank you so much!

My pleasure! Happy you found it useful :-)
