### ISSUE TITLE
Recommendation for miRge3 for non-model organism

### ISSUE THREAD

**Issue by cement-head** [marta-nazzari/CODA#2]
For an organism not listed here: https://mirge3.readthedocs.io/en/latest/quick_start.html#mirge3-0-libraries

Would you recommend downloading all of them?  I am studying an amphibian (frog).

**Comment by marta-nazzari** [comment]
Hi Andor,
I am not sure I understand you question. If the library of the organism you are interested in is not among the ones that the miRge3 developers created, it is possible to make it yourself following the instruction suggested by the same developers using mirge-build (https://mirge-build.readthedocs.io/en/latest/index.html#).
Check also my reply to a previous issue https://github.com/marta-nazzari/CODA/issues/1#issuecomment-1378533052.
Let me know if this answered your question or not  :-)


Cheers,
Marta

**Comment by cement-head** [comment]
I guess if I don't have some of these files:
![image](https://github.com/marta-nazzari/CODA/assets/1056700/5aa6a61a-92a7-4232-aae1-8fe4fedb3633)
I'm a little unclear as to where I would obtain and/or generate them? Or would most of these get generated in the GFF annotation?
